//
//  VitaMindIntents.swift
//  VitaMindGo
//
//  App Intents for the A2A (Agent-to-Agent) trend. Exposes VitaMindGo's
//  core features to Siri, Shortcuts, and other Apple Intelligence agents.
//
//  Phase 1 (v3.1.0+): 2 intents
//   1. GetHealthSummaryIntent  - read-only, returns today's steps/sleep/heart
//   2. LogHabitIntent          - write action, marks a named habit done
//
//  All intents use SHARED SERVICES (HealthKitService, PersistenceService)
//  directly, NOT GameState. This is the correct pattern for App Intents —
//  they should be stateless and not depend on UI state. The same data
//  sources feed the in-app UI, so the two stay in sync.
//
//  Privacy: All operations are local. No data leaves the device.
//
//  iOS 16+ required for AppIntents framework; deployment target iOS 17.0+.
//

import AppIntents
import Foundation

// MARK: - GetHealthSummaryIntent

/// Returns a brief summary of today's health metrics (steps, sleep, heart rate).
///
/// Example Siri phrases (auto-generated by AppShortcutsProvider):
///   - "Hey Siri, get my health summary from VitaMindGo"
///   - "Hey Siri, what's my step count in VitaMindGo"
struct GetHealthSummaryIntent: AppIntent {
    static let title: LocalizedStringResource = "Get Health Summary"
    static let description = IntentDescription(
        "Returns a brief summary of today's health metrics: steps, sleep, and heart rate."
    )

    /// Run in background — no need to open the app for a quick read.
    static let openAppWhenRun: Bool = false

    func perform() async throws -> some IntentResult & ProvidesDialog {
        let healthKit = HealthKitService.shared

        // Trigger an up-to-date snapshot. HealthKitService has its own
        // caching; fetchAllData() refreshes today's metrics from HealthKit.
        await healthKit.fetchAllData()

        let steps = healthKit.todaySteps
        let sleep = healthKit.todaySleepHours
        let heart = healthKit.todayHeartRate

        if steps <= 0 && sleep <= 0 && heart <= 0 {
            return .result(dialog: IntentDialog(stringLiteral:
                "I don't have any health data for today yet. Make sure HealthKit is connected in VitaMindGo Settings."
            ))
        }

        var parts: [String] = []
        if steps > 0    { parts.append("\(Int(steps)) steps") }
        if sleep > 0    { parts.append(String(format: "%.1f hours of sleep", sleep)) }
        if heart > 0    { parts.append("\(Int(heart)) BPM") }
        let summary = "Today: " + parts.joined(separator: ", ") + "."
        return .result(dialog: IntentDialog(stringLiteral: summary))
    }
}

// MARK: - LogHabitIntent

/// Marks a habit as completed for today. Matches the user's existing habits
/// by case-insensitive substring. Awards XP and updates streak.
///
/// Example Siri phrases:
///   - "Hey Siri, log 'drink water' in VitaMindGo"
///   - "Hey Siri, mark my morning run done in VitaMindGo"
struct LogHabitIntent: AppIntent {
    static let title: LocalizedStringResource = "Log Habit"
    static let description = IntentDescription(
        "Mark a named habit as completed for today in VitaMindGo."
    )

    static let openAppWhenRun: Bool = false

    @Parameter(title: "Habit Name",
               description: "The habit to mark done (e.g. 'drink water')")
    var habitName: String

    func perform() async throws -> some IntentResult & ProvidesDialog {
        let trimmed = habitName.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            return .result(dialog: IntentDialog(stringLiteral:
                "Please tell me which habit to log, like 'log drink water'."
            ))
        }

        // Load all habits, find match, mark done, save.
        var habits = PersistenceService.shared.loadHabitCards()
        guard !habits.isEmpty else {
            return .result(dialog: IntentDialog(stringLiteral:
                "You don't have any habits yet. Add some in VitaMindGo first."
            ))
        }

        // Case-insensitive substring match
        let lower = trimmed.lowercased()
        let matchIndex: Int? = habits.firstIndex(where: { $0.name.lowercased() == lower })
            ?? habits.firstIndex(where: { $0.name.lowercased().contains(lower) })

        guard let index = matchIndex else {
            // No match — suggest the 3 closest by string length
            let suggestions = habits
                .sorted { abs($0.name.count - lower.count) < abs($1.name.count - lower.count) }
                .prefix(3)
                .map { $0.name }

            if suggestions.isEmpty {
                return .result(dialog: IntentDialog(stringLiteral:
                    "I couldn't find a habit matching '\(trimmed)'. Add it in VitaMindGo first."
                ))
            } else {
                let list = suggestions.joined(separator: ", ")
                return .result(dialog: IntentDialog(stringLiteral:
                    "I couldn't find '\(trimmed)'. Did you mean: \(list)?"
                ))
            }
        }

        let name = habits[index].name
        if habits[index].isCompletedToday {
            return .result(dialog: IntentDialog(stringLiteral:
                "'\(name)' is already logged for today. Keep the streak going!"
            ))
        }

        habits[index].isCompletedToday = true
        habits[index].currentStreak += 1
        habits[index].lastCompleted = Date()
        if habits[index].currentStreak > habits[index].longestStreak {
            habits[index].longestStreak = habits[index].currentStreak
        }
        PersistenceService.shared.saveHabitCards(habits)

        let streak = habits[index].currentStreak
        return .result(dialog: IntentDialog(stringLiteral:
            "Logged '\(name)' for today. \(streak) day streak!"
        ))
    }
}

// MARK: - AppShortcutsProvider

/// Registers the intents with Siri / Shortcuts so users can invoke them
/// by voice. The `phrases` array uses the `\.applicationName` token which
/// is automatically replaced with the app's display name (e.g. "VitaMindGo").
struct VitaMindAppShortcuts: AppShortcutsProvider {

    /// Background tint color for the Shortcuts app icon (optional).
    static let shortcutTileColor: ShortcutTileColor = .purple

    static var appShortcuts: [AppShortcut] {
        AppShortcut(
            intent: GetHealthSummaryIntent(),
            phrases: [
                "Get my \(.applicationName) health summary",
                "Show my health stats in \(.applicationName)",
                "What's my day in \(.applicationName)"
            ],
            shortTitle: "Health Summary",
            systemImageName: "heart.text.square"
        )

        AppShortcut(
            intent: LogHabitIntent(),
            phrases: [
                "Log a habit in \(.applicationName)",
                "Mark a habit done in \(.applicationName)"
            ],
            shortTitle: "Log Habit",
            systemImageName: "checkmark.circle"
        )
    }
}
